export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_REQUEST = 'GET_REQUEST';
export const CHANNELS_ERROR = 'CHANNELS_ERROR';
export const FETCH_CHANNELS = 'FETCH_CHANNELS';
export const CURRENT_PAGE = 'CURRENT_PAGE';
